Breakfast-Header test
EugenePustovit/gidmenuQA pull request #4
Opened 2021-01-03 23:30 UTC by ke-de-ve

https://trello.com/c/7LzHiMUw/17-breakfasts-header-test

2021-01-04 16:56 UTC, maximashuev submitted a review, later dismissed

2021-01-05 19:00 UTC, VictoriaRogo commented on Tests/BreakfastsPage_test.py
> +class TestHomePage:
Why the class name is TestHomePage?

2021-01-06 03:31 UTC, ke-de-ve commented on Tests/BreakfastsPage_test.py
> +class TestHomePage:
renamed

2021-01-06 19:19 UTC, Stan575 submitted a review, later dismissed

2021-01-06 19:19 UTC, Stan575 commented on Config/TestData.py
> +    BREAKFASTS_PAGE_URL = 'https://gidmenu.com/restaurants/zavtraki/'
you can use HOME_PAGE_URL to construct new page url

2021-01-09 04:16 UTC, VictoriaRogo submitted a review, later dismissed

2021-01-09 04:35 UTC, Stan575 requested changes

2021-01-09 04:35 UTC, Stan575 commented on Tests/BreakfastsPage_test.py
> +        sleep(5)
Please delete sleep and import for sleep

2021-01-09 04:35 UTC, Stan575 commented on Tests/BreakfastsPage_test.py
> +#    @pytest.mark.parametrize('restaurant', TestData.RESTAURANT_COLLECTION)
Commented out code in repository is bad practice

2021-01-10 11:03 UTC, maximashuev requested changes

2021-01-10 11:03 UTC, maximashuev commented on Config/TestData.py
> +    RESTAURANT_COLLECTION = [PATRIARSHIE_PRUDY]
Please delete lines 6-11.they are not related to this test.

2021-01-12 19:28 UTC, ke-de-ve commented on Config/TestData.py
> +    RESTAURANT_COLLECTION = [PATRIARSHIE_PRUDY]
they will be related later when page is fully implemented

2021-01-12 19:50 UTC, maximashuev commented on Config/TestData.py
> +    RESTAURANT_COLLECTION = [PATRIARSHIE_PRUDY]
they are not part of your task and your TC
they should not be included here

2021-01-14 04:01 UTC, merged